name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
    # What's Changed
    $CHANGES
categories:
  - title: ⚠️ Breaking changes
    labels:
      - 'breaking change'
  - title: 🔒 Security
    labels:
      - 'security'
  - title: 🚀 Features & Enhancements
    labels:
      - 'enhancement'
  - title: ☠️ Deprecations
    label: type/deprecation
  - title: 🐛 Bug Fixes
    labels:
      - 'bug'
  - title: 📖 Documentation
    labels:
      - 'documentation'
  - title: 🧹 Housekeeping
    labels:
      - 'chore'
  - title: 📦 Dependency updates
    label: dependencies
