version: "2"
linters:
  default: all
  disable:
    - depguard
    - errchkjson
    - exhaustruct
    - funlen
    - gocognit
    - godox
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - tagalign
    - testpackage
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    godot:
      scope: all
    gosec:
      excludes:
        - G601
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    nestif:
      min-complexity: 10
    nolintlint:
      require-explanation: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - wrapcheck
        path: _test\.go
      - linters:
          - mnd
        text: 'Magic number: 0o\d+'
      - path: _test\.go
        text: fieldalignment
      - linters:
          - err113
        text: 'do not define dynamic errors, use wrapped static errors instead:'
      - linters:
          - forcetypeassert
        path: mock_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
