# on-push GitHub Actions workflow
name: "on-push"
on:
  - push
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: attempt to package it
      run: docker build -t qminder/moby-ryuk .
